// Writes tree-element's stylesheet to src/styles.ts, so the component can add
// it to the page without a css import that needs bundler support.
import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const cssPath = require.resolve("tree-element/tree_element.css");
const css = fs.readFileSync(cssPath, "utf8");

const { version } = JSON.parse(
  fs.readFileSync(path.join(path.dirname(cssPath), "package.json"), "utf8"),
);

const source = `// Generated by config/generateStyles.mjs from tree-element ${version}. Do not edit.
const styles: string = ${JSON.stringify(css)};

export default styles;
`;

const target = path.join(import.meta.dirname, "../src/styles.ts");

if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== source) {
  fs.writeFileSync(target, source);
}
